# Title shown in Application Information tab.
title: Marketplace Groups and Policies
# Sub Title shown in Application Information tab.
description: Stack to create Marketplace service policy and user groups and policies
schemaVersion: 1.1.0
version: "20190304"

locale: "en"
variableGroups:
  - title: "Hidden Variable Group"
    visible: false
    variables:
#"variables used internally - not exposed to end user"
      - tenancy_ocid
      - region

  - title: "Service Policy"
    variables:
      - create_service_policy
     
  - title: "User Groups and Policies"
    variables:
      - create_publisher_group_policy
      - create_offer_group_policy
      - create_buyer_group_policy

######################################################
##############          VARIABLES        #############
######################################################

variables:

##############    HIDDEN VARIABLES       #############

  tenancy_ocid:
    type: string
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: The region in which to create all resources
    required: true


##############   VARIABLES   #############

  create_service_policy:
    type: boolean
    title: Create Service Policy
    description: The service policy allows Marketplace read access to image & stack resources for publication in tenancy.
    default: true
    required: true

  create_publisher_group_policy:
    type: boolean
    title: Create Publisher Group and Policy
    description: Creates a group in the default domain and policy with admin permissions for Marketplace resources in tenancy.
    default: true
    required: true

  create_offer_group_policy:
    type: boolean
    title: Create Private Offer Group and Policy
    description: Creates a group in the default domain and policy with admin permissions for Private Offers sellers.
    default: true
    required: true

  create_buyer_group_policy:
    type: boolean
    title: Create Private Offer Buyer Group and Policy
    description: Creates a group in the default domain and policy with admin permissions for Private Offers buyers (for testing).
    default: true
    required: true